wordlist = {
    'scrummaster': 'A facilitator in an agile development team',
    'developer': 'A person who develops',
    'addition': 'The action of adding a value to another value',
    'subtraction': 'The action of removing one number from another number or value',
    'division': 'The action of separating something into smaller parts',
    'multiplication': 'The action of multiplying',
    'lyntax': 'Our team name',
    'language': 'A system of notation for writing computer programs',
    'syntax':  'Rules that define the structure of a language',
    'error': 'The occurrence of an incorrect result produced by a computer',
    'debugging': 'The process of identifying and correcting errors',
    'algorithm': 'A list of instructions to be carried out',
    'ifstatement': 'A logical block which will execute the following code if a given condition is true',
    'elsestatement': 'A statement which describes what to do if a given condition is not true',
    'whileloop': 'A block of code which will run itself repeatedly until a condition is met',
    'float': 'A number written with a decimal',
    'integer': 'A whole number',
    'boolean': 'A variable which can only be either true or false',
    'conditional': 'Commands which perform different actions depending on weather a boolean condition evaluates the statement to be true or false',
    'function': 'Self contained modules of code that accomplish a specific task',
    'directory': 'A file system cataloging structure which contains references to other computer files',
    'variable': 'A value that can change, depending on conditions or on information passed to the program',
    'sprites': 'A two-dimensional image or animated image that plays a specific role, often independently manipulated, within a larger image environment.',
    'jupyter': 'A free, open-source, interactive web tool known as a computational notebook, which researchers can use to combine software code, computational output, explanatory text and multimedia resources in a single document.',
    'markdown': 'A markup language that formats plain text',
    'binary': 'A system where numbers and values are expressed 0 or 1',
    'array': 'A data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.',
    'dictionary': 'An abstract data type that defines an unordered collection of data as a set of key-value pairs.',
    'list': 'An abstract data type that represents a finite number of ordered values, where the same value may occur more than once.',
    'argument': 'The actual input expression passed/supplied to a function, procedure, or routine in the invocation/call statement', 
    'input': 'Data that is entered into or received by a computer',
    'output': 'Any information processed by and sent out from a computer or other electronic device',
    'string': 'A series of readable or usable sentences that the user will use',
    'parameter': 'Variables for the values the function needs. Is passed as an argument when the function is called'
}